version: 2.1
jobs:
  build:
    docker:
      - image: centos:7 # the primary container, where your job's commands are run
        auth:
          username: mydockerhub-user
          password: $DOCKERHUB_PASSWORD  # context / project UI env-var reference
    steps:
      - checkout # check out the code in the project directory
      - run: echo "hello world" #  run the `echo` command
      - run: hostname
      - run: cat /etc/redhat-release
      - run: echo "hello again"
